AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  QueueName:
    Type: String
    Description: Name of the main queue. DLQ should be called "${QueueName}_dead_letter"
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logging
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: sqs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:ChangeMessageVisibilityBatch
            - sqs:DeleteMessage
            - sqs:DeleteMessageBatch
            - sqs:GetQueueAttributes
            - sqs:GetQueueUrl
            - sqs:ListQueues
            - sqs:ReceiveMessage
            - sqs:SendMessage
            - sqs:SendMessageBatch
            Resource: !Join
            - ":"
            -
              - "arn:aws:sqs"
              - !Ref "AWS::Region"
              - !Ref "AWS::AccountId"
              - !Join
                - ""
                -
                  - !Ref QueueName
                  - "*"
  RequeueFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join
      - "-"
      -
        - !Ref "AWS::StackName"
        - Requeue
        - !Ref QueueName
      Description: Requeues messages from dead letter queue
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Join
        - "-"
        -
          - "lambda-functions"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
        S3Key: requeue_lambda.zip
      Environment:
        Variables:
          QUEUE_NAME: !Ref QueueName
      Runtime: python2.7
      Timeout: 60
